### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by dcj** [bojanrajkovic/vaping-exporter#2]
I'm running vaping-exporter on OpenBSD 6.1, with vaping version 1.1.0.
After a few hours, an exception is thrown and the process exits:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 185, in _run
    self.emit_all()
  File "/usr/local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 162, in emit_all
    self.send_emission()
  File "/usr/local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 154, in send_emission
    emit()
  File "/usr/local/lib/python2.7/site-packages/vaping/plugins/__init__.py", line 142, in emit
    emitter.emit(msg)
  File "/usr/local/etc/vaping/plugins/prometheus.py", line 25, in emit
    min_latency.labels(host_name).observe(host_data.get('min'))
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/metrics.py", line 424, in observe
    self._sum.inc(amount)
  File "/usr/local/lib/python2.7/site-packages/prometheus_client/values.py", line 20, in inc
    self._value += amount
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
2019-08-20T22:08:19Z <FPing "latency" at 0x7bf2e533158: _run> failed with TypeError

**Comment by spanthetree** [comment]
@dcj It's been a while since you made this comment, and I've just discovered this plugin, but I was having the same problem. So I did some digging and I found the problem to exist in the following:

```
vaping.plugins.prometheus data: [{'host': '10.33.56.1', 'cnt': 10, 'loss': 0.2, 'data': [16.17, 19.71, 13.92, 16.72, 19.69, 11.83, 5.71, 15.5], 'min': 5.71, 'max': 19.71, 'avg': 14.90625, 'last': 15.5}, {'host': '10.33.0.122', 'cnt': 10, 'loss': 1.0, 'data': []}] prometheus.py:24
vaping.plugins.fping popen fping -u -C10 -p20 -e 10.33.56.1 10.33.0.122 __init__.py:102
root 10.33.56.1  : - 19.85 3.67 1.59 11.07 10.09 8.85 4.45 1.75 4.54
 fping.py:90
root 10.33.0.122 : - - - - - - - - - -
 fping.py:90
```

You'll notice that sometimes fping returns a list of nothing but hyphens (indicating 100% loss, i think.. or "no response"). In that case, the fping plugin for vaping does not return "data" (which is the full output of fping, minus any "-" that were returned by fping), nor does it return anything in 'min', 'max', or 'avg'. Herein lies the problem, as this prometheus exported is expecting that the returned data from vaping.plugins.fping contains all of those fields.

You could mitigate this either by
1. fixing the return in vaping.plugins.fping so that it always returns something in all fields,
2. you could tell this prometheus exporter to only emit the above fields if they actually exist.

As I think option 2 is fairly harmless, I'll create a PR demonstrating that. Maybe if gets merged, maybe not :)
